OBJS	=	euler	pi	prime	sorted	median	reverse

all:	$(OBJS)

euler:	euler.hs
	ghc	euler.hs

pi:	pi.hs
	ghc	pi.hs

prime:
	ghc	prime.hs

sorted:
	ghc	sorted.hs

reverse:
	ghc	reverse.hs

median:
	ghc	median.hs

clean:	
	$(RM)	*.hi	*.o	$(OBJS)
