OBJS	=	color-comic	asciimation	map

all:	$(OBJS)

color-comic:	color-comic.hs
	ghc	color-comic.hs

asciimation:	asciimation.hs
	ghc	asciimation.hs

map:	map.hs
	ghc	map.hs
clean:	
	$(RM)	*.hi	*.o	$(OBJS)
